# Generated by Django 2.0.5 on 2018-10-17 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alldata',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
