# Generated by Django 2.0.5 on 2018-11-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_allsalehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsalehouse',
            name='square',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
