# Generated by Django 2.0.5 on 2018-11-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_allsalehouse_square'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allsalehouse',
        ),
    ]
