# Generated by Django 2.0.5 on 2018-11-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_allsalehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allsalehouse',
        ),
    ]
