# Generated by Django 2.0.5 on 2018-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20181121_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alldealhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=20)),
                ('hurl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('deal_price', models.CharField(max_length=15)),
                ('deal_date', models.CharField(max_length=15)),
                ('backup1', models.CharField(default='', max_length=20)),
                ('backup2', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
