# Generated by Django 2.0.5 on 2018-11-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alldata_snumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsalehouse',
            name='backup3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='allsalehouse',
            name='dat_t_30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allsalehouse',
            name='day_t_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allsalehouse',
            name='day_t_7',
            field=models.IntegerField(default=0),
        ),
    ]
