# Generated by Django 2.0.5 on 2018-11-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20181123_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldata',
            name='dayd',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='dayu',
        ),
        migrations.AddField(
            model_name='alldata',
            name='dayud',
            field=models.CharField(default='', max_length=15),
        ),
    ]
