# Generated by Django 2.0.5 on 2018-11-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20181123_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allsalehouse',
            old_name='dat_t_30',
            new_name='day_t_30',
        ),
    ]
