# Generated by Django 2.0.5 on 2018-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20181123_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allljshequ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('lprice', models.CharField(max_length=10)),
                ('lhis', models.CharField(max_length=1000)),
                ('ldistrict', models.CharField(max_length=10)),
                ('lbiz', models.CharField(max_length=10)),
                ('lyear', models.CharField(max_length=10)),
                ('lurl', models.CharField(max_length=70)),
                ('backup1', models.CharField(default='', max_length=20)),
                ('backup2', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
