# Generated by Django 2.0.5 on 2018-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_allljshequ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allajkshequ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=20)),
                ('kname', models.CharField(max_length=20)),
                ('ktype', models.CharField(max_length=10)),
                ('kfee', models.CharField(max_length=10)),
                ('kyear', models.CharField(max_length=10)),
                ('kdense', models.CharField(max_length=10)),
                ('kurl', models.CharField(max_length=70)),
                ('kprice', models.CharField(default='', max_length=10)),
                ('khis', models.CharField(max_length=2000)),
                ('backup1', models.CharField(default='', max_length=20)),
                ('backup2', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
