# Generated by Django 2.0.5 on 2018-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_allajkshequ'),
    ]

    operations = [
        migrations.AddField(
            model_name='allljshequ',
            name='trend',
            field=models.CharField(default='', max_length=5),
        ),
    ]
