# Generated by Django 2.0.5 on 2018-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20181128_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('unitprice', models.CharField(max_length=15)),
                ('shequ_name', models.CharField(max_length=40)),
                ('shape', models.CharField(max_length=10)),
                ('square', models.CharField(max_length=10)),
                ('ori', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=20)),
                ('hurl', models.CharField(max_length=100)),
                ('isSold', models.BooleanField(default=False)),
                ('shequ_id', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
