# Generated by Django 2.0.5 on 2018-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_allpies'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpies',
            name='ptype',
            field=models.CharField(default='', max_length=5),
        ),
    ]
