# Generated by Django 2.0.5 on 2018-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_allpies_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allljbrokers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=20)),
                ('jdistrict', models.CharField(max_length=20)),
                ('jname', models.CharField(max_length=10)),
                ('jposition', models.CharField(max_length=10)),
                ('jrating', models.CharField(max_length=5)),
                ('jshop', models.CharField(max_length=15)),
                ('jtel', models.CharField(max_length=20)),
                ('jyear', models.CharField(max_length=10)),
                ('jsold', models.CharField(max_length=5)),
                ('jvisit30', models.CharField(max_length=5)),
                ('rsold', models.CharField(max_length=200)),
                ('rvisit', models.CharField(max_length=200)),
                ('backup1', models.CharField(default='', max_length=20)),
                ('backup2', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
