# Generated by Django 2.0.5 on 2019-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_allljbrokers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allshequdealhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=20)),
                ('lid', models.CharField(max_length=20)),
                ('hurl', models.CharField(max_length=100)),
                ('ldistrict', models.CharField(max_length=10)),
                ('shequ_name', models.CharField(max_length=20)),
                ('shape', models.CharField(max_length=10)),
                ('square', models.CharField(max_length=10)),
                ('ori', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=20)),
                ('deal_date', models.CharField(max_length=15)),
                ('deal_price', models.CharField(max_length=15)),
                ('backup1', models.CharField(default='', max_length=20)),
                ('backup2', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
